CREATE TABLE IF NOT EXISTS test_with_stats (
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    META_BUILD VARCHAR(64) NOT NULL,
    CLASS_NAME VARCHAR(512) NOT NULL,
    TEST_NAME  VARCHAR(512) NOT NULL,
    COUNT      BIGINT DEFAULT 0,
    TOTAL_TIME BIGINT DEFAULT 0,
    SUCCESSES  BIGINT DEFAULT 0,
    FAILURES   BIGINT DEFAULT 0
    );

CREATE TABLE IF NOT EXISTS test_case_results (
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    TEST_ID     BIGINT NOT NULL,
    TIMESTAMP   BIGINT NOT NULL,
    COMMIT_HASH VARCHAR(41) NOT NULL,
    BUILD_KEY   VARCHAR(256) NOT NULL,
    STATUS      VARCHAR(8) NOT NULL,
    FLAKYINESS  INT DEFAULT 0,
    foreign key (TEST_ID) references test_with_stats(TEST_ID)
    );